# fly.toml app configuration file generated for celeo-spirit-box-bot on 2023-05-03T14:48:31-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "celeo-spirit-box-bot"
primary_region = "lax"
kill_signal = "SIGINT"
kill_timeout = "5s"
